version: '3.8'
services:
  api:
    image: api
    build: .
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    restart: unless-stopped
    depends_on:
      - mongo
  mongodb:
    image: mongo
    ports:
      - 27017:27017
