version: '3.8'
services:
  api:
    image: api
    build: .
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    restart: unless-stopped
    environment: 
     - PORT=3001
     - MONGO_URI=mongodb+srv://rod-trips:4iDPA97TSTcUX52m@cluster0.yrffebo.mongodb.net/
    #depends_on:
     # - mongo
  #mongodb:
   # image: mongo
   # ports:
    #  - 27018:27018
